---
- hosts: openshift
  
  vars:
    my_rhpass: "{{rhpass}}"
    my_rhpass: "{{rhpass}}"
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.6-rpms
      - rhel-7-fast-datapath-rpms

  tasks:
  - name: Register and subscribe to multiple pools
    redhat_subscription:
      tags: deploy
      state: present
      username: "{{my_rhuser}}"
      password: "{{my_rhuser}}"
      pool_ids:
       - 8a85f9815ee99f8e015ee9e09e2e7809
  
  - name: Add repositories
    yum_repository:
      name: "{{item}}"
      with_items: repos

      
