---
- hosts: openshift
  gather_facts: no
  
  vars:
    # my_rhuser: "{{rhuser}}"
    my_rhuser: "DXC1_Steven.Wake"
    my_rhpass: "{{rhpass}}"
    http_proxy: http://10.0.4.2:80
    redhat_openshift_sub_pool_id : 8a85f981592b0c6501592be7f43b73a8
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.6-rpms
      - rhel-7-fast-datapath-rpms

  environment:
    http_proxy: "{{http_proxy}}"

  tasks:
  - name: configure firewall
    become: true
    lineinfile:
      path: /etc/yum.conf
      regexp: ^proxy=
      line: proxy={{http_proxy}}


  - name: Register and subscribe to multiple pools
    become: true
    redhat_subscription:
      state: present
      username: "{{my_rhuser}}"
      password: "{{my_rhuser}}"
      pool_ids: 
        - "{{redhat_openshift_sub_pool_id}}"
      # autosubscribe: true
  
  - name: Add repositories
    yum_repository:
      name: "{{item}}"
      with_items: repos

      


#   ansible all -i=",$server" --become -m lineinfile -a "path=/etc/yum.conf regexp='^proxy=' line='proxy=http://16.85.88.10:8080'" || true
