---
- hosts: all
  gather_facts: false
  connection: local

  vars:
    my_vcuser: "{{vcuser}}"
    my_vcpass: "{{vcpass}}"
    my_rhpass: "{{rhpass}}"
    my_rhpass: "{{rhpass}}"

    domain_suffix: .dppoc.uk
    servers_with_items:
    - name: "ocpinfranodeV{{ domain_suffix }}"
      staticip: 10.0.7.139
    - name: "ocpmasterV{{ domain_suffix }}"
      staticip: 10.0.7.141
    - name: "ocpmaster1V{{ domain_suffix }}"
      staticip: 10.0.7.140
    - name: "ocpnode1V{{ domain_suffix }}"
      staticip: 10.0.7.138
    - name: "ocpnode2V{{ domain_suffix }}"
      staticip: 10.0.7.137




#Deploy guests with tag deploy  
  tasks:
  - name: deploy guests
    tags: deploy
    with_items: "{{ servers_with_items }}"
    vmware_guest:
      hostname: ukrdvmgvc001.dbpoc.uk
      validate_certs: no
      username: "{{my_vcuser}}"
      password: "{{my_vcpass}}"
      name: "{{ item.name }}"
      template: DXC-RHEL7.4-TEMPLATE
      cluster: Reading-Dev-PoC
      datacenter: Reading-Dev
      resource_pool: Reading-Dev-PoC
      # datastore:  ukrd_esx_mgmt_data_002
      state: poweredon
      hardware:
        memory_mb: 2048
        num_cpus: 2
      networks:
      - name: Containers_204
        ip: "{{ item.staticip }}"
        netmask: 255.255.255.0
        gateway: 10.0.7.1
        dns_servers:
        - 30.5.86.7
        - 30.5.86.8
        type: static




#remove guests with tag remove
  # - name: power off guests
  #   tags: remove
  #   with_items: "{{ servers_with_items }}"
  #   vsphere_guest:
  #     vcenter_hostname: ukrdvmgvc001.dbpoc.uk
  #     validate_certs: no
  #     username: "{{my_vcuser}}"
  #     password: "{{my_vcpass}}"
  #     guest: "{{ item.name }}"
  #     state: powered_off

  - name: remove guests
    tags: remove
    with_items: "{{ servers_with_items }}"
    vsphere_guest:
      state: absent
      force: yes
      vcenter_hostname: ukrdvmgvc001.dbpoc.uk
      validate_certs: no
      username: "{{my_vcuser}}"
      password: "{{my_vcpass}}"
      guest: "{{ item.name }}"
