---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    my_vcuser: "{{vcuser}}"
    my_vcpass: "{{vcpass}}"
    datacenter : Reading-Dev
    my_public_key: ~/.ssh/dxckubespraydev.pub
    my_sshpass: vagrant
    vm_datastore: ukrd_esx_mgmt_data_002
    domain_suffix: dbpoc.uk
    servers_with_items:
    - name: ocpinfranodeV
      docker_disk_size: 100GB
      memory: 8192
      datastore: "{{vm_datastore}}"
      staticip: 10.0.7.139
    - name: ocpmasterV
      docker_disk_size: 100GB
      memory: 8192
      datastore: "{{vm_datastore}}"
      staticip: 10.0.7.141
    - name: ocpmaster1V
      docker_disk_size: 100GB
      memory: 8192
      datastore: "{{vm_datastore}}"
      staticip: 10.0.7.140
    - name: ocpnode1V
      docker_disk_size: 200GB
      memory: 16384
      datastore: "{{vm_datastore}}"
      staticip: 10.0.7.138
    - name: ocpnode2V
      docker_disk_size: 200GB
      memory: 16384
      datastore: "{{vm_datastore}}"
      staticip: 10.0.7.137
               
  tasks:

#Remove guests with tag remove
  - name: remove guests
    tags: remove
    with_items: "{{ servers_with_items }}"
    vsphere_guest:
      state: absent
      force: yes
      vcenter_hostname: ukrdvmgvc001.dbpoc.uk
      validate_certs: no
      username: "{{my_vcuser}}"
      password: "{{my_vcpass}}"
      guest: "{{ item.name }}"


#Deploy guests with tag deploy  

  - name: deploy guests
    tags: deploy
    with_items: "{{ servers_with_items }}"
    vmware_guest:
      hostname: ukrdvmgvc001.dbpoc.uk
      validate_certs: no
      username: "{{my_vcuser}}"
      password: "{{my_vcpass}}"
      name: "{{ item.name }}"
      template: DXC-RHEL7.4-TEMPLATE
      cluster: Reading-Dev-PoC
      datacenter: "{{datacenter}}"
      resource_pool: Reading-Dev-PoC
      # datastore:  ukrd_esx_mgmt_data_002
      state: poweredon
      hardware:
        memory_mb: "{{ item.memory }}"
        num_cpus: 2
      disk: 
      - size: 20GB
        datastore: "{{item.datastore}}"
      - size: "{{ item.docker_disk_size }}"
        datastore: "{{item.datastore}}"
      networks:
      - name: Containers_204
        ip: "{{ item.staticip }}"
        netmask: 255.255.255.0
        gateway: 10.0.7.1
        dns_servers:
        - 30.5.86.7
        - 30.5.86.8
        type: static
      customization:
        dns_servers:
        - 30.5.86.7
        - 30.5.86.8
        domain: "{{ domain_suffix }}"
      wait_for_ip_address : yes

#Configure guests with tag configure
  # - name: Remove any old keys in your host auth checker 
  #   tags: configure
  #   with_items: "{{ servers_with_items}}"
  #   local_action: command ocpinfranodeV


  - name: Configure security | Deploy key 
    tags: configure
    with_items: "{{ servers_with_items}}"
    local_action: command sshpass -p {{my_sshpass}} ssh-copy-id -o  UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i {{my_public_key}} vagrant@{{item.name}}




#remove guests with tag remove
  # - name: power off guests
  #   tags: remove
  #   with_items: "{{ servers_with_items }}"
  #   vsphere_guest:
  #     vcenter_hostname: ukrdvmgvc001.dbpoc.uk
  #     validate_certs: no
  #     username: "{{my_vcuser}}"
  #     password: "{{my_vcpass}}"
  #     guest: "{{ item.name }}"
  #     state: powered_off

