---
- hosts: openshift
  
  vars:
    my_rhuser: "{{rhuser}}"
    my_rhpass: "{{rhpass}}"
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.6-rpms
      - rhel-7-fast-datapath-rpms

  tasks:
  - name: Register and subscribe to multiple pools
    become: true
    redhat_subscription:
      state: present
      username: "{{my_rhuser}}"
      password: "{{my_rhuser}}"
      # autosubscribe: true
  
  # - name: Add repositories
  #   yum_repository:
  #     name: "{{item}}"
  #     with_items: repos

      
