---
- hosts: openshift
  gather_facts: no
  
  vars:
    # my_rhuser: "{{rhuser}}"
    my_rhuser: "DXC_Steven.Wake"
    my_rhpass: "{{rhpass}}"
    http_proxy: http://10.0.4.2:80
    redhat_openshift_sub_pool_id : 8a85f9815eb84c2f015eb8634aa42f8d
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.6-rpms
      - rhel-7-fast-datapath-rpms

  environment:
    http_proxy: "{{http_proxy}}"

  tasks:
  - name: configure yum proxy
    become: true
    lineinfile:
      path: /etc/yum.conf
      regexp: ^proxy=
      line: proxy={{http_proxy}}


  - name: Register
    become: true
    command: "subscription-manager register --force --username {{my_rhuser}} --password={{my_rhpass}}"

  - name: Remove all repos
    yum_repository:
      name: "*"
      state: absent

  - name: subscribe to pool
    become: true
    redhat_subscription:
      username: "{{my_rhuser}}"
      password: "{{my_rhpass}}"
      pool_ids: 
        - "{{redhat_openshift_sub_pool_id}}"
  
  - name: Add repositories
    become: true
    command: "subscription-manager repos --enable={{ item }}"
    with_items: "{{repos}}"

  - name: disable firewalld
    become: true
    systemd:
      name: firewalld
      state: stopped
      enabled: false
      
  - name: install the prerequisite packages
    become: true
    yum:
      name: "{{item}}"
    with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Install docker
    become: true
    yum:
      name: docker-1.12.6

  - name: install the openshift excluder
    become: true
    yum:
      name: "{{item}}"
    with_items:
    - atomic-openshift-utils
    - atomic-openshift
    - atomic-openshift-excluder 
    - atomic-openshift-docker-excluder

  - name: Set up excluder
    become: true
    command: atomic-openshift-excluder unexclude

