---
- hosts: openshift
  gather_facts: no
  
  vars:
    # my_rhuser: "{{rhuser}}"
    my_rhuser: "DXC_Steven.Wake"
    my_rhpass: "{{rhpass}}"
    http_proxy: http://10.0.4.2:80
    redhat_openshift_sub_pool_id : 8a85f9815eb84c2f015eb8634aa42f8d
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.6-rpms
      - rhel-7-fast-datapath-rpms

  environment:
    http_proxy: "{{http_proxy}}"

  tasks:
  - name: configure yum proxy
    become: true
    lineinfile:
      path: /etc/yum.conf
      regexp: ^proxy=
      line: proxy={{http_proxy}}


  - name: Register and subscribe to multiple pools
    become: true
    redhat_subscription:
      state: present
      username: "{{my_rhuser}}"
      password: "{{my_rhpass}}"
      pool_ids: 
        - "{{redhat_openshift_sub_pool_id}}"
  
  - name: Remove all repos
    yum_repository:
      name: "*"
      state: absent

  - name: Add repositories
    become: true
    command: "subscription-manager repos --enable={{ item }}"
    with_items: "{{repos}}"

  - name: disable firewalld
    become: true
    systemd:
      name: firewalld
      state: stopped
      enabled: false


  - name: install the openshift installer
    become: true
    yum:
      name: atomic-openshift-utils
      state: latest
      
