---
- hosts: openshift
  tasks:
  - name: Register and subscribe to multiple pools
    redhat_subscription:
      tags: deploy
      state: present
      username: "{{my_rhuser}}"
      password: "{{my_rhuser}}"
      pool_ids:
       - 0123456789abcdef0123456789abcdef
       - 1123456789abcdef0123456789abcdef

  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      
