---
- hosts: openshift
  tasks:
  - name: Register and subscribe to multiple pools
    redhat_subscription:
      tags: deploy
      state: present
      username: "{{my_rhuser}}"
      password: "{{my_rhuser}}"
      pool_ids:
       - 8a85f9815ee99f8e015ee9e09e2e7809
  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      
